name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Porter
      uses: jeremyrickard/porter-gh-action@master
    - uses: azure/docker-login@v1
      name: Docker Login
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Porter Publish
      run: porter publish
